# Generated by Django 4.2.4 on 2023-08-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
